import Head from 'next/head'
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
      </Head>

      <main >

        <div className="container mt-5">
          <div className="row justify-content-center">
            <div className="col-md-8 text-center">
              <h1>Welcome to Contact Manager</h1>
              <p>A web application that allows you to manage your contacts efficiently</p>
            </div>
          </div>

          <div className="row justify-content-center mt-4">
            <div className="col-lg-4 col-md-6">
              <div className="card">
                <div className="card-body text-center">
                  <h5 className="card-title">Browse List</h5>
                  <p className="card-text">View and manage your existing contacts in a table format.</p>
                  <Link href={'/contacts/Contacts'}>  <p className="btn btn-success">
                    Browse
                  </p>
                  </Link>
                </div>
              </div>
            </div>

            <div className="col-lg-4 col-md-6">
              <div className="card">
                <div className="card-body text-center">
                  <h5 className="card-title">Add New </h5>
                  <p className="card-text">Add a new contact to your list with ability to edit.</p>
                  <Link href={'/contacts/Add'}>
                    <p className="btn btn-primary">Add</p>
                  </Link>
                </div>
              </div>
            </div>
          </div>

        </div>
        <footer className="fixed-bottom bg-light text-white text-center py-2">
          <p className='text-dark'> &copy;  {new Date().getFullYear()}  M.KHALID.K.AGHA All rights reserved</p>
          <a href="https://www.linkedin.com/in/khalid-agha/" target="_blank" rel="noopener noreferrer">
            <i className='bi bi-linkedin text-dark mx-3'></i>
          </a>
          <a href="https://github.com/KhalidAgha-2000" target="_blank" rel="noopener noreferrer">
            <i className='bi bi-github text-dark mx-3'></i>
          </a>
        </footer>

      </main >
    </>
  )
}
